plugins:
  disraptor_enabled:
    default: false
    client: true
  disraptor_shadow_dom:
    default: false
    client: true
  disraptor_app_secret_key:
    default: ''
    secret: true
  disraptor_read_timeout:
    default: 120
    client: true
